//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.867609
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////


/// 18-05. Added comments. 


/////////////////////////////////////////////////////////////
// The main purpose of the bridge is to translate serial communication in ASCII 
// to functions in the Arduino's firmware.

#include "inodriver_bridge.h"

SerialCommand sCmd;

void ok() {
  Serial.println("OK");
}

void error(const char* msg) {
  Serial.print("ERROR: ");
  Serial.println(msg);
}

void error_i(int errno) {
  Serial.print("ERROR: ");
  Serial.println(errno);
}


/// .available checks if there's space in the buffer.
/// if > 0 then we have bytes waiting for it to be read
// so .readSerial then reads the bytes.

void bridge_loop() {
  while (Serial.available() > 0) {
    sCmd.readSerial();
  }
}

void bridge_setup() {
  //// Setup callbacks for SerialCommand commands

  // All commands might return
  //    ERROR: <error message>

  // All set commands return 
  //    OK 
  // if the operation is successfull

  // All parameters are ascii encoded strings
  sCmd.addCommand("INFO?", getInfo); 

  sCmd.setDefaultHandler(unrecognized); 

  // initialize

  // Thanks to sCmd.addCommand('TEXT', wrapperFUNCTION)
  // there's a connection between the function INITIALIZE
  // and the text (in ASCII) INITIALIZE.
  // This is the general idea of the addCommand method.

  // A wrapper is a intermediate-function that adapts the interface
  // between one function and another. In this case, it would be
  // between the addCommand function and the Call_INITIALIZE function.

  // Call:
  //   INITIALIZE
  // Returns: OK or ERROR  
  sCmd.addCommand("INITIALIZE", wrapperCall_INITIALIZE); 

  // Call:
  //   FINALIZE
  // Returns: OK or ERROR  
  sCmd.addCommand("FINALIZE", wrapperCall_FINALIZE); 

  /////////////////////
  //// Ptico
  /////////////////////
   
  ////// Motor

  // Setter:
  //    STEP <I>
  // Returns: OK or ERROR
  sCmd.addCommand("STEP", wrapperSet_STEP);

  // Setter:
  // Returns: OK or ERROR
  sCmd.addCommand("ZERO", wrapperSet_ZERO);

  ////// Led Controller

  // Setter:
  //    INTENSITY <I>
  // Returns: OK or ERROR
  sCmd.addCommand("INTENSITY1", wrapperSetLedIntensity1);

  // Call:
  // Returns: OK or ERROR
  sCmd.addCommand("TURNOFFLED1", wrapperCallLedTurnOff1);

  // Setter:
  //    INTENSITY <I>
  // Returns: OK or ERROR
  sCmd.addCommand("INTENSITY1", wrapperSetLedIntensity2);

  // Call:
  // Returns: OK or ERROR
  sCmd.addCommand("TURNOFFLED1", wrapperCallLedTurnOff2);

  ////// Sensor

  // Query:
  // Returns: Value or ERROR
  sCmd.addCommand("SENSOR?", wrapperQuerySignal);

  /////////////////
  //// PROYECTO SEMILLAS, no borrar.
  /////////////////
}
/*
  // Setter:
  //   FREQUENCY <I>
  // Returns: OK or ERROR 
  sCmd.addCommand("FREQUENCY", wrapperSet_FREQUENCY); 

  // Setter:
  //   TMODE <I> <I>
  // Returns: OK or ERROR  
  sCmd.addCommand("TMODE", wrapperSet_TMODE); 

  /////////////////
  //// MODES
  /////////////////

  // Setter:
  //   MODE <I>
  //  <I> 
  //    0: fixed
  //    1: external
  //    2: timed
  //    3: triggered
  // Returns: OK or ERROR 
  sCmd.addCommand("MODE", wrapperSet_MODE); 

  /////////////////
  //// FIXED
  /////////////////

  // Setter:
  //   PHASE <I>
  // Returns: OK or ERROR 
  sCmd.addCommand("PHASE", wrapperSet_PHASE); 

  /////////////////
  //// EXTERNAL 
  /////////////////

  /////////////////
  //// TIMED 
  //// TRIGGERED 
  /////////////////

  // Setter:
  //   DELTA <I> 
  // Returns: OK or ERROR 
  sCmd.addCommand("DELTA", wrapperSet_DELTA); 

  // Setter:
  //   TIMESTEP <I> 
  // Returns: OK or ERROR  
  sCmd.addCommand("TIMESTEP", wrapperSet_TIMESTEP); 

  // Call:
  //   PAUSE
  // Returns: OK or ERROR  
  sCmd.addCommand("PAUSE", wrapperCall_PAUSE);   

  // Setter:
  //   NSTEPS <I>
  // Returns: OK or ERROR  
  sCmd.addCommand("NSTEPS", wrapperSet_NSTEPS); 

  //////////////
  /// FUTURE 
  //////////////

  // Call:
  //   ACQUIRE <I>
  // Returns: OK or ERROR  
  sCmd.addCommand("ACQUIRE", wrapperCall_ACQUIRE); 

  // Call:
  //   GETDATA
  // Returns: OK or ERROR  
  sCmd.addCommand("GETDATA", wrapperCall_GETDATA); 
*/
//// Code 

void getInfo() {
  Serial.print("DephasedPWM,");
  Serial.println(COMPILE_DATE_TIME);
}

void unrecognized(const char *command) {
  error("Unknown command");
}
//// Auto generated Feat and DictFeat Code
// COMMAND: INITIALIZE, Action: initialize

void wrapperCall_INITIALIZE() {
  int err = call_INITIALIZE();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

// COMMAND: FINALIZE, Action: finalize

void wrapperCall_FINALIZE() {
  int err = call_FINALIZE();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

////////////////////////////////
// Pticografia
///////////////////////////////

// Motor

void wrapperSet_STEP() {
  char *arg;

  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  uint32_t step = atol(arg);
  Set_STEP(step);
  ok();
};

void wrapperSet_ZERO() {
  int err = Set_ZERO();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

// Led Controler

void wrapperSetLedIntensity1() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int intensity = atol(arg);
  if (intensity > 0 && intensity < 255) {
    Set_INTENSITY1(intensity);
    ok();
  } else {
    error("invalid value, must be larger than 0 and smaller than 255");
  }
}

void wrapperCallLedTurnOff1() {
  int err = Call_TURNOFF1();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
}

void wrapperSetLedIntensity2() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int intensity = atol(arg);
  if (intensity > 0 && intensity < 255) {
    Set_INTENSITY2(intensity);
    ok();
  } else {
    error("invalid value, must be larger than 0 and smaller than 255");
  }
}

void wrapperCallLedTurnOff2() {
  int err = Call_TURNOFF2();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
}

// Sensor IR

void wrapperQuerySignal(){
  int err = QuerySignal();
  if (err == 0) {} 
  else {
    error_i(err);
  }
}

////////////////////////////////
// Proyecto Semillas, no borrar
///////////////////////////////


/*
void wrapperSet_FREQUENCY() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  uint32_t frequency = atol(arg);
  if (frequency > 0) {
    set_FREQUENCY(frequency);
    ok();
  } else {
    error("invalid value, must be larger than 0");
  }
}

void wrapperSet_MODE() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int mode = atoi(arg);
  switch (mode) {
    case 0:
      set_MODE(fixed);
      break;
    case 1:
      set_MODE(external);
      break;
    case 2:
      set_MODE(timed);
      break;
    case 3:
      set_MODE(triggered);
      break;   
    default:
      error("invalid value, must be 0 (fixed), 1 (external), 2 (timed), 3 (triggered)");
      break;
  }
  ok();
};

void wrapperSet_PHASE() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int phase = atoi(arg);
  if (phase >= 0 && phase <= 360) {
    set_PHASE(phase);
    ok();
  } else {
    error("invalid value, must be between 0 and 360");
  }
}

void wrapperSet_DELTA() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int delta = atoi(arg);
  if ((delta >= 1 && delta <= 45) || (delta >= -45 && delta <= -1)) {
    set_DELTA(delta);
    ok();
  } else {
    error("invalid value, must be between 1 and 45 (positive or negative)");
  }
}

void wrapperSet_TIMESTEP() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int timestep = atoi(arg);
  if (timestep >= 10 && timestep <= 100) {
    set_TIMESTEP(timestep);
    ok();
  } else {
    error("invalid value, must be between 10 and 100");
  }
}

void wrapperSet_NSTEPS() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No step value stated");
    return;
  }
  int steps = atoi(arg);
  if (steps >= 0 && steps <= 1000) {

  } else {
    error("invalid step value, must be between 1 and 1000, or 0 to disable bidirectional scanning.");
  }
  set_NSTEPS(steps);
  ok();
}

void wrapperSet_TMODE() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No transducer value stated");
    return;
  }
  int transducer = atoi(arg);
  if (transducer >= 1 && transducer <= 2) {

  } else {
    error("invalid tranducer value, must be between 1 and 2");
  }
  arg = sCmd.next();
  if (arg == NULL) {
    error("No phase value stated");
    return;
  }
  int mode = atoi(arg);
  if ((mode >= 0) && (mode <= 2)) {

  } else {
    error("invalid mode value, must be 0 (disabled), 1 (input mode), 2 (output mode)");
  }
  set_TMODE(transducer, mode);
  ok();
}

void wrapperCall_PAUSE() {
  int err = call_PAUSE();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

void wrapperCall_ACQUIRE() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  uint32_t frequency = atol(arg);
  if (frequency > 0) {

  } else {
    error("invalid value, must be larger than 0");
  }

  int err = call_ACQUIRE(frequency);
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

void wrapperCall_GETDATA() {
  int err = call_GETDATA();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

*/