//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.868531
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////

/// 18-05. Added comments. 


// If the bridge is the communication between the PC and the Arduino firmware
// the inodriver_user is the communication between the Arduino user and the hardware.
// For every function call in the bridge, we must define it in the user.


#ifndef inodriver_user_h
#define inodriver_user_h

#include <Arduino.h>
#include "Motor.h"
#include "LedController.h"
#include "SensorIR.h"

void user_setup();
void user_loop();

int call_INITIALIZE(); 
int call_FINALIZE(); 

// Motor functions
int16_t Set_STEP(long step);
int16_t Set_ZERO();
// Led Controler functions
int16_t Set_INTENSITY1(int intensity);
int16_t Call_TURNOFF1();
int16_t Set_INTENSITY2(int intensity);
int16_t Call_TURNOFF2();
// Sensor functions
int16_t QuerySignal();

/*
int16_t set_MODE(PhaseControlMode);
int16_t set_FREQUENCY(uint32_t);
int16_t set_PHASE(uint16_t);
int16_t set_DELTA(int16_t); 
int16_t set_TIMESTEP(int16_t);
int16_t set_NSTEPS(int16_t);
int16_t set_TMODE(int16_t, int16_t);
int16_t call_PAUSE();

int16_t call_ACQUIRE(uint32_t);
int16_t call_GETDATA();
*/

#endif // inodriver_user_