//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.867609
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////


/// 18-05. Added comments. 
/// 08-06. Created a copy for future reference and deleted unnecessary lines.
/// 19-06. Removed unnecesary comments. Added parking call function and wrapper.

#include "inodriver_bridge.h"
extern Parking parking;

SerialCommand sCmd;

void ok() {
  Serial.println("OK");
}

void ok_park() {
  Serial.println("PARK_OK");
}

void error(const char* msg) {
  Serial.print("ERROR: ");
  Serial.println(msg);
}

void error_i(int errno) {
  Serial.print("ERROR: ");
  Serial.println(errno);
}

void bridge_loop() {
  while (Serial.available() > 0) {
    sCmd.readSerial();
  }
}

void bridge_setup() {
  //// Setup callbacks for SerialCommand commands

  // All commands might return
  //    ERROR: <error message>

  // All set commands return 
  //    OK 
  // if the operation is successfull

  // All parameters are ascii encoded strings
  sCmd.addCommand("INFO?", getInfo); 

  sCmd.setDefaultHandler(unrecognized); 

  // Call:
  //   INITIALIZE
  // Returns: OK or ERROR  
  sCmd.addCommand("INITIALIZE", wrapperCall_INITIALIZE); 

  // Call:
  //   FINALIZE
  // Returns: OK or ERROR  
  sCmd.addCommand("FINALIZE", wrapperCall_FINALIZE); 

  /////////////////////
  //// Ptycography
  /////////////////////
   
  ////// Motor

  // Setter:
  //    STEP <I>
  // Returns: OK or ERROR
  sCmd.addCommand("STEP", wrapperSet_STEP);

  // Setter:
  // Returns: OK or ERROR
  sCmd.addCommand("ZERO", wrapperSet_ZERO);

  // Setter:
  // Returns: OK or ERROR
  sCmd.addCommand("POS?", wrapperQueryPosition);

  ////// Led Controller

  // Setter:
  //    INTENSITY <I>
  // Returns: OK or ERROR
  sCmd.addCommand("INTENSITY1", wrapperSetLedIntensity1);

  // Call:
  // Returns: OK or ERROR
  sCmd.addCommand("TURNOFFLED1", wrapperCallLedTurnOff1);

  // Setter:
  //    INTENSITY <I>
  // Returns: OK or ERROR
  sCmd.addCommand("INTENSITY2", wrapperSetLedIntensity2);

  // Call:
  // Returns: OK or ERROR
  sCmd.addCommand("TURNOFFLED2", wrapperCallLedTurnOff2);

  ////// Sensor

  // Query:
  // Returns: Value or ERROR
  sCmd.addCommand("SENSOR?", wrapperQuerySignal);

  ////// Parking
  
  //Call:
  // Returns: OK or ERROR
  sCmd.addCommand("PARK", wrapperCall_PARK);
}

//////// Code 

void getInfo() {
  Serial.print("DephasedPWM,");
  Serial.println(COMPILE_DATE_TIME);
}

void unrecognized(const char *command) {
  error("Unknown command");
}
//// Auto generated Feat and DictFeat Code
// COMMAND: INITIALIZE, Action: initialize

void wrapperCall_INITIALIZE() {
  int err = call_INITIALIZE();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

// COMMAND: FINALIZE, Action: finalize

void wrapperCall_FINALIZE() {
  int err = call_FINALIZE();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

////////////////////////////////
// Ptycography
///////////////////////////////

/////// Motor


void wrapperSet_STEP() {
  char *arg;

  arg = sCmd.next();

  Serial.print("STEP recibido: ");
  Serial.println(arg);

  uint32_t step = atol(arg);

  Set_STEP(step);

  ok();
}

void wrapperSet_ZERO() {
  int err = Set_ZERO();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

void wrapperQueryPosition(){
  Serial.println(QueryPosition());
};

////// Led Controler

void wrapperSetLedIntensity1() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int intensity = atol(arg);
  if (intensity > 0 && intensity < 255) {
    Set_INTENSITY1(intensity);
    ok();
  } else {
    error("invalid value, must be larger than 0 and smaller than 255");
  }
}

void wrapperCallLedTurnOff1() {
  int err = Call_TURNOFF1();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
}

void wrapperSetLedIntensity2() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int intensity = atol(arg);
  if (intensity > 0 && intensity < 255) {
    Set_INTENSITY2(intensity);
    ok();
  } else {
    error("invalid value, must be larger than 0 and smaller than 255");
  }
}

void wrapperCallLedTurnOff2() {
  int err = Call_TURNOFF2();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
}

// Sensor IR


void wrapperQuerySignal(){
  Serial.println(QuerySignal());
}


void wrapperCall_PARK() {
  bool result = parking.Execute();

  if (result) {
    Serial.println("PARK_OK");
  } else {
    Serial.println("PARK_FAIL");
  }
}