//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> PLEASE ADAPT IT TO YOUR NEEDS <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.868531
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////


// 18-05. Added comments. 
// 27-05. Added functions for  Fourier ptycography, mainly motor controller.
// 29-05. Added functions for Fourier ptycography microscope, mainly now for some LED Controllers with PWM.
/// 08-06. Created a copy for future reference and deleted unnecessary lines.

#include "inodriver_user.h"


// setting.h is include since the last project have several constants
// for setting-up the hardware.

#include "settings.h"

/*
DephasedPWM dephased_pwm(
  CFG_TRANSDUCER_1_OUTPUT_PIN, 
  CFG_TRANSDUCER_2_OUTPUT_PIN, 
  CFG_TRANSDUCER_INVERT_HELPER_PIN, 
  CFG_TRANSDUCER_2_DEPHASE_EXT_PIN, 
  CFG_TRANSDUCER_2_DEPHASE_PAUSE_PIN,
  CFG_TRANSDUCER_PHASE_TRIGGER_PIN,
  CFG_TRANSDUCER_PHASE_CHANGING_PIN
);

SimpleAnalogInput simple_ai(
  CFG_TRANSDUCER_1_INPUT_PIN, 
  CFG_TRANSDUCER_2_INPUT_PIN
);

AIOSwitch tranducer1(
  CFG_TRANSDUCER_1_INPUT_RELAY_PIN, 
  CFG_TRANSDUCER_1_INPUT_RELAY_CONN_STATE, 
  CFG_TRANSDUCER_1_OUTPUT_RELAY_PIN, 
  CFG_TRANSDUCER_1_OUTPUT_RELAY_CONN_STATE, 
  CFG_TRANSDUCER_MODE_DELAY
);

AIOSwitch tranducer2(
  CFG_TRANSDUCER_2_INPUT_RELAY_PIN, 
  CFG_TRANSDUCER_2_INPUT_RELAY_CONN_STATE, 
  CFG_TRANSDUCER_2_OUTPUT_RELAY_PIN, 
  CFG_TRANSDUCER_2_OUTPUT_RELAY_CONN_STATE, 
  CFG_TRANSDUCER_MODE_DELAY
);
*/

const uint8_t pinDir = 48;
const uint8_t pinStep = 50;
const uint8_t maxSpeed = 300.0;
const uint8_t acceleration = 100.0;
const uint8_t pinLed1 = 8;
const uint8_t pinLed2 = 9;
const uint8_t pinSensor = A1;

Motor motor(pinStep, pinDir, maxSpeed, acceleration);
LedController ledcontroller1(pinLed1);
LedController ledcontroller2(pinLed2);
SensorIR sensor(pinSensor);
Parking parking(motor, sensor);

// Here we initialize the different functions we need to execute one time.
// This a different instances of the classes. e.g. tranducer1 & tranducer2 are
// two different instances of the class AIOSwitch.

void user_setup() {
  motor.init();
  ledcontroller1.init();
  ledcontroller2.init();
  sensor.init();
  parking.Execute();
  // dephased_pwm.init();
  // simple_ai.init();
  // tranducer1.init();
  // tranducer2.init();
  
};

void user_loop() {
  motor.runtime();
  ledcontroller1.runtime();
  ledcontroller2.runtime();
  sensor.runtime();
  // dephased_pwm.runtime();
  // simple_ai.runtime();
  // tranducer1.runtime();
  // tranducer2.runtime();
};

int call_INITIALIZE() {
  return 0;
};

int call_FINALIZE() {
  return 0;
};

//////////////////
/// Proyecto PTICO
//////////////////

// Funciones del motor.

int16_t Set_STEP(long step) {
  motor.moveAbsolute(step);
  return 0;
}

int16_t Set_ZERO() {
  motor.setCurrentPositionAsZero();
  return 0;
}

int16_t QueryPosition() {
  motor.queryPosition();
  return 0;
}

// Funciones del controlador LED

int16_t Set_INTENSITY1(int intensity) {
  ledcontroller1.LedIntensity(intensity);
  return 0;
}

int16_t Call_TURNOFF1() {
  ledcontroller1.LedTurnOff();
  return 0;
}

int16_t Set_INTENSITY2(int intensity) {
  ledcontroller2.LedIntensity(intensity);
  return 0;
}

int16_t Call_TURNOFF2() {
  ledcontroller2.LedTurnOff();
  return 0;
}

// Funciones del sensor IR

int16_t QuerySignal() {
  sensor.querySignal();
  return 0;
}


/*
int16_t set_FREQUENCY(uint32_t frequency) {
  dephased_pwm.setFrequency(frequency);
  return 0;
}

int16_t set_MODE(PhaseControlMode mode) {
  dephased_pwm.setMode(mode);
  return 0;
}

int16_t set_PHASE(uint16_t phase) {
  dephased_pwm.setPhase(phase);
  return 0;
}

int16_t set_DELTA(int16_t delta) {
  dephased_pwm.setDelta(delta);
  return 0;
}


int16_t set_TIMESTEP(int16_t timestep) {
  dephased_pwm.setTimeStep(timestep);
  return 0;
}

int16_t set_NSTEPS(int16_t steps) {
  dephased_pwm.setStepsBidir(steps);
  return 0;
}

int16_t set_TMODE(int16_t transducer, int16_t mode) {
  AIOMode new_mode;
  if (mode == 0) {
    new_mode = disabled;
  } else if (mode == 1) {
    new_mode = input;
  } else if (mode == 2) {
    new_mode = output;
  }
  if (transducer == 1) {
    tranducer1.setMode(new_mode);
  } else if (transducer == 2) {
    tranducer2.setMode(new_mode);
  }
  return 0;
}

int16_t call_PAUSE() {
  dephased_pwm.pause();
  return 0;
}

int16_t call_ACQUIRE(uint32_t frequency) {
  simple_ai.acquire(frequency);
  return 0;
}

int16_t call_GETDATA() {
  simple_ai.BufferToSerial();
  return 0;
}
*/
