//// ****** THIS FILE IS AUTOGENERATED ******
////
////          >>>> DO NOT CHANGE <<<<
////
/// 
///  Filename; /Users/grecco/Documents/code/spim/spim/drivers/arduino.py
///  Source class: MultiController
///  Generation timestamp: 2019-05-23T23:42:14.867609
///  Class code hash: d1b05b40a9df1b4a1656d0c3765fd920b632719c
///
/////////////////////////////////////////////////////////////


/// 18-05. Added comments. 
/// 08-06. Created a copy for future reference and deleted unnecessary lines.

/////////////////////////////////////////////////////////////
// The main purpose of the bridge is to translate serial communication in ASCII 
// to functions in the Arduino's firmware.

#include "inodriver_bridge.h"

SerialCommand sCmd;

void ok() {
  Serial.println("OK");
}

void error(const char* msg) {
  Serial.print("ERROR: ");
  Serial.println(msg);
}

void error_i(int errno) {
  Serial.print("ERROR: ");
  Serial.println(errno);
}


/// .available checks if there's space in the buffer.
/// if > 0 then we have bytes waiting for it to be read
// so .readSerial then reads the bytes.

void bridge_loop() {
  while (Serial.available() > 0) {
    sCmd.readSerial();
  }
}

void bridge_setup() {
  //// Setup callbacks for SerialCommand commands

  // All commands might return
  //    ERROR: <error message>

  // All set commands return 
  //    OK 
  // if the operation is successfull

  // All parameters are ascii encoded strings
  sCmd.addCommand("INFO?", getInfo); 

  sCmd.setDefaultHandler(unrecognized); 

  // initialize

  // Thanks to sCmd.addCommand('TEXT', wrapperFUNCTION)
  // there's a connection between the function INITIALIZE
  // and the text (in ASCII) INITIALIZE.
  // This is the general idea of the addCommand method.

  // A wrapper is a intermediate-function that adapts the interface
  // between one function and another. In this case, it would be
  // between the addCommand function and the Call_INITIALIZE function.

  // Call:
  //   INITIALIZE
  // Returns: OK or ERROR  
  sCmd.addCommand("INITIALIZE", wrapperCall_INITIALIZE); 

  // Call:
  //   FINALIZE
  // Returns: OK or ERROR  
  sCmd.addCommand("FINALIZE", wrapperCall_FINALIZE); 

  /////////////////////
  //// Ptico
  /////////////////////
   
  ////// Motor

  // Setter:
  //    STEP <I>
  // Returns: OK or ERROR
  sCmd.addCommand("STEP", wrapperSet_STEP);

  // Setter:
  // Returns: OK or ERROR
  sCmd.addCommand("ZERO", wrapperSet_ZERO);

  // Setter:
  // Returns: OK or ERROR
  sCmd.addCommand("POS?", wrapperQueryPosition);

  ////// Led Controller

  // Setter:
  //    INTENSITY <I>
  // Returns: OK or ERROR
  sCmd.addCommand("INTENSITY1", wrapperSetLedIntensity1);

  // Call:
  // Returns: OK or ERROR
  sCmd.addCommand("TURNOFFLED1", wrapperCallLedTurnOff1);

  // Setter:
  //    INTENSITY <I>
  // Returns: OK or ERROR
  sCmd.addCommand("INTENSITY2", wrapperSetLedIntensity2);

  // Call:
  // Returns: OK or ERROR
  sCmd.addCommand("TURNOFFLED2", wrapperCallLedTurnOff2);

  ////// Sensor

  // Query:
  // Returns: Value or ERROR
  sCmd.addCommand("SENSOR?", wrapperQuerySignal);
}

//// Code 

void getInfo() {
  Serial.print("DephasedPWM,");
  Serial.println(COMPILE_DATE_TIME);
}

void unrecognized(const char *command) {
  error("Unknown command");
}
//// Auto generated Feat and DictFeat Code
// COMMAND: INITIALIZE, Action: initialize

void wrapperCall_INITIALIZE() {
  int err = call_INITIALIZE();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

// COMMAND: FINALIZE, Action: finalize

void wrapperCall_FINALIZE() {
  int err = call_FINALIZE();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

////////////////////////////////
// Pticografia
///////////////////////////////

// Motor

void wrapperSet_STEP() {
  char *arg;

  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  uint32_t step = atol(arg);
  Set_STEP(step);
  ok();
};

void wrapperSet_ZERO() {
  int err = Set_ZERO();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
};

void wrapperQueryPosition(){
  int err = QueryPosition();
  if (err == 0) {} 
  else {
    error_i(err);
  }
}

// Led Controler

void wrapperSetLedIntensity1() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int intensity = atol(arg);
  if (intensity > 0 && intensity < 255) {
    Set_INTENSITY1(intensity);
    ok();
  } else {
    error("invalid value, must be larger than 0 and smaller than 255");
  }
}

void wrapperCallLedTurnOff1() {
  int err = Call_TURNOFF1();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
}

void wrapperSetLedIntensity2() {
  char *arg;
  
  arg = sCmd.next();
  if (arg == NULL) {
    error("No value stated");
    return;
  }
  int intensity = atol(arg);
  if (intensity > 0 && intensity < 255) {
    Set_INTENSITY2(intensity);
    ok();
  } else {
    error("invalid value, must be larger than 0 and smaller than 255");
  }
}

void wrapperCallLedTurnOff2() {
  int err = Call_TURNOFF2();
  if (err == 0) {
    ok();
  } else {
    error_i(err);
  }
}

// Sensor IR

void wrapperQuerySignal(){
  int err = QuerySignal();
  if (err == 0) {} 
  else {
    error_i(err);
  }
}
