// Arduino Uno configuration

const uint8_t CFG_TRANSDUCER_PHASE_TRIGGER_PIN = 11;
const uint8_t CFG_TRANSDUCER_PHASE_CHANGING_PIN = 13;

const uint8_t CFG_TRANSDUCER_1_OUTPUT_PIN = 9;
const uint8_t CFG_TRANSDUCER_2_OUTPUT_PIN = 10;
const uint8_t CFG_TRANSDUCER_INVERT_HELPER_PIN = 8;
const uint8_t CFG_TRANSDUCER_2_DEPHASE_EXT_PIN = 4;
const uint8_t CFG_TRANSDUCER_2_DEPHASE_PAUSE_PIN = 12;

const uint8_t CFG_TRANSDUCER_1_INPUT_PIN = A0;
const uint8_t CFG_TRANSDUCER_2_INPUT_PIN = A1;

const uint8_t CFG_TRANSDUCER_1_INPUT_RELAY_PIN = 5;
const uint8_t CFG_TRANSDUCER_1_INPUT_RELAY_CONN_STATE = HIGH;
const uint8_t CFG_TRANSDUCER_1_OUTPUT_RELAY_PIN = 1;
const uint8_t CFG_TRANSDUCER_1_OUTPUT_RELAY_CONN_STATE = HIGH;

const uint8_t CFG_TRANSDUCER_2_INPUT_RELAY_PIN = 2;
const uint8_t CFG_TRANSDUCER_2_INPUT_RELAY_CONN_STATE = HIGH;
const uint8_t CFG_TRANSDUCER_2_OUTPUT_RELAY_PIN = 3;
const uint8_t CFG_TRANSDUCER_2_OUTPUT_RELAY_CONN_STATE = HIGH;

const uint8_t CFG_TRANSDUCER_MODE_DELAY = 200;
